# Generated by Django 5.2.4 on 2026-07-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='crp',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]