# Generated by Django 5.2.4 on 2026-07-14 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userprofile'),
    ]

    operations = [
    ]