# Generated by Django 5.2.4 on 2026-07-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userprofile'),
        ('chat', '0003_userprofile_crp'),
    ]

    operations = [
    ]
