# Generated by Django 5.2.4 on 2026-09-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_userprofile_next_session_at_userprofile_psychologist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='emotions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='checkin',
            name='factors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
