# Generated by Django 5.2.4 on 2026-09-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_checkin_emotions_checkin_factors'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='sentimento',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
