# Generated by Django 5.2.4 on 2026-09-01 16:58

import app.chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_diaryentry_sentimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability_end_time',
            field=models.TimeField(default=app.chat.models.default_end_time),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='availability_slot_duration',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='availability_start_time',
            field=models.TimeField(default=app.chat.models.default_start_time),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='working_days',
            field=models.JSONField(blank=True, default=app.chat.models.default_working_days),
        ),
        migrations.CreateModel(
            name='CalendarAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('cancellation_message', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_appointments_as_patient', to=settings.AUTH_USER_MODEL)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_appointments_as_psychologist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
    ]
