# Generated by Django 5.2.4 on 2026-09-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_calendarappointment_reschedule_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blocked_dates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
